version: "2.2"
services:
  jenkins:
    image: jenkins:jcasc
    container_name: jenkins
    build: .
    ports:
      - "8080:8080"
    environment:
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: password
    networks:
      - jenkins-nw

networks:
  jenkins-nw:
